appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: eYRuWz/2PsSPn0rA+kDlL4u6u1+MjKcZ92geoiNFAHLUtkzcyKUpFc/qA1lgjT8vUzATJVliq8ohYCoGMo3ZDHUQlRNjc+jVgt10ny0Qfwnz/FpMsijVqZLD4p5fNMZN8MvxTwBO0QT+8Z66Gveyb2XT0Sps+egwKLX4T3q9YY44LyxbVHMQjFGR6Rei7l9yDjyVmGcqR8Ai6FwhyNh1Xv6fk4nAk9eRXemgy5S8OjHywY1oEfpwSbILOUHOjarIlZvLcxp0dAABaKualdLJkzMLFQS3K4k5ztd4llJzfGInEoOboN9n+nR5i5htFRrH4XkplJ+I6nhbxJCiJjYoILy6n7pQ5ouPQCOXH+Ocm6a4rqwlr1pJ4U3f4dOAsAoIqTiEZC7wBxZ37GWF/4h7ndVi493XwxDR8JX+4060IJRXYeyUoR7u0VdXcf5kSfrkI1h3U67EOd9PW3dh2QG3ncTSoLouYWUdMCopmiLSyizSW4XHoFMfxlZBfdQo7Ux3MGIEsZdWy8gtbgYLaGHJvqGYDa5GRIXsk4cNPiHj43SOc/4H1CxA/6DNAVvSFRa5Fp1iR1MvbkhVKvXuQ1ho9LksvXcHYYMwa3jt/FqWjtDrTNIj4mKICbK5NAX5C91A/RCaWNHJLWWBthBoVsabIKOioLh7buNwCQKgLF7Abcs=}
conda_forge_output_validation: true
